// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TUP_Materias.Data;

#nullable disable

namespace TUP_Materias.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260528041435_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TUP_Materias.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("MateriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("TUP_Materias.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProfesorAsignadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorAsignadoId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("TUP_Materias.Models.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("TUP_Materias.Models.Alumno", b =>
                {
                    b.HasOne("TUP_Materias.Models.Materia", null)
                        .WithMany("AlumnosInscriptos")
                        .HasForeignKey("MateriaId");
                });

            modelBuilder.Entity("TUP_Materias.Models.Materia", b =>
                {
                    b.HasOne("TUP_Materias.Models.Profesor", "ProfesorAsignado")
                        .WithMany()
                        .HasForeignKey("ProfesorAsignadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfesorAsignado");
                });

            modelBuilder.Entity("TUP_Materias.Models.Materia", b =>
                {
                    b.Navigation("AlumnosInscriptos");
                });
#pragma warning restore 612, 618
        }
    }
}
